#!/usr/bin/env bash
# deploy-anvil.sh
# 一鍵部署所有合約到本地 Anvil，並匯出 ABI + addresses 到 frontend/src/contracts/
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$REPO_ROOT/contracts"
FRONTEND_CONTRACTS="$REPO_ROOT/frontend/src/contracts"
RPC_URL="http://localhost:8545"
# Anvil account-0 default private key (never use in production)
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
CHAIN_ID=31337

# ── 1. Build ─────────────────────────────────────────────────────────────────
echo "[1/4] Building contracts..."
cd "$CONTRACTS_DIR"
forge build --silent

# ── 2. Deploy ────────────────────────────────────────────────────────────────
echo "[2/4] Deploying to Anvil ($RPC_URL)..."
forge script script/Deploy.s.sol \
    --rpc-url   "$RPC_URL" \
    --private-key "$PRIVATE_KEY" \
    --broadcast \
    -v

# ── 3. Extract addresses from broadcast JSON ──────────────────────────────────
echo "[3/4] Extracting addresses..."
BROADCAST="$CONTRACTS_DIR/broadcast/Deploy.s.sol/$CHAIN_ID/run-latest.json"

addr() { jq -r --arg n "$1" \
    '.transactions[] | select(.transactionType=="CREATE" and .contractName==$n) | .contractAddress' \
    "$BROADCAST"; }

USDC_ADDR=$(addr "MockUSDC")
ORACLE_ADDR=$(addr "MockOracle")
FEEROUTER_ADDR=$(addr "FeeRouter")
EXCHANGE_ADDR=$(addr "PerpetualExchange")
REGISTRY_ADDR=$(addr "StrategyRegistry")
TRACKER_ADDR=$(addr "CopyTracker")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "  %-22s %s\n" "MockUSDC:"          "$USDC_ADDR"
printf "  %-22s %s\n" "MockOracle:"        "$ORACLE_ADDR"
printf "  %-22s %s\n" "FeeRouter:"         "$FEEROUTER_ADDR"
printf "  %-22s %s\n" "PerpetualExchange:" "$EXCHANGE_ADDR"
printf "  %-22s %s\n" "StrategyRegistry:"  "$REGISTRY_ADDR"
printf "  %-22s %s\n" "CopyTracker:"       "$TRACKER_ADDR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── 4. Export ABI + addresses to frontend ─────────────────────────────────────
echo "[4/4] Exporting to frontend..."
mkdir -p "$FRONTEND_CONTRACTS/abi"
cd "$REPO_ROOT"

for name in MockUSDC MockOracle FeeRouter PerpetualExchange StrategyRegistry CopyTracker; do
    jq '.abi' "contracts/out/$name.sol/$name.json" \
        > "$FRONTEND_CONTRACTS/abi/$name.json"
done

# Compute asset IDs (keccak256 of the symbol string)
SBTC_ID=$(cast keccak  "sBTC")
SETH_ID=$(cast keccak  "sETH")
SAAPL_ID=$(cast keccak "sAAPL")
STSLA_ID=$(cast keccak "sTSLA")

cat > "$FRONTEND_CONTRACTS/addresses.ts" <<TSEOF
// Auto-generated by deploy-anvil.sh — do not edit ANVIL section manually
// Sepolia section updated automatically by deploy-sepolia.sh

export interface ChainAddresses {
  MockUSDC:          string
  MockOracle:        string
  FeeRouter:         string
  PerpetualExchange: string
  StrategyRegistry:  string
  CopyTracker:       string
}

// ── Anvil local (chainId 31337) ───────────────────────────────────────────────
const ANVIL: ChainAddresses = {
  MockUSDC:          "$USDC_ADDR",
  MockOracle:        "$ORACLE_ADDR",
  FeeRouter:         "$FEEROUTER_ADDR",
  PerpetualExchange: "$EXCHANGE_ADDR",
  StrategyRegistry:  "$REGISTRY_ADDR",
  CopyTracker:       "$TRACKER_ADDR",
}

// ── Sepolia testnet (chainId 11155111) ────────────────────────────────────────
const SEPOLIA: ChainAddresses = {
  MockUSDC:          "0x0000000000000000000000000000000000000000",
  MockOracle:        "0x0000000000000000000000000000000000000000",
  FeeRouter:         "0x0000000000000000000000000000000000000000",
  PerpetualExchange: "0x0000000000000000000000000000000000000000",
  StrategyRegistry:  "0x0000000000000000000000000000000000000000",
  CopyTracker:       "0x0000000000000000000000000000000000000000",
}

const CHAIN_MAP: Record<number, ChainAddresses> = {
  31337:    ANVIL,
  11155111: SEPOLIA,
}

export const getAddresses = (chainId: number | null): ChainAddresses | null =>
  chainId === null ? null : (CHAIN_MAP[chainId] ?? null)

export const CHAIN_NAMES: Record<number, string> = {
  31337:    'Anvil Local',
  11155111: 'Sepolia',
}

// keccak256 of symbol string — matches Deploy.s.sol and on-chain IDs
export const ASSET_IDS = {
  sBTC:  "$SBTC_ID"  as \`0x\${string}\`,
  sETH:  "$SETH_ID"  as \`0x\${string}\`,
  sAAPL: "$SAAPL_ID" as \`0x\${string}\`,
  sTSLA: "$STSLA_ID" as \`0x\${string}\`,
} as const

// Initial oracle prices (8-decimal, same as MockOracle storage)
export const INITIAL_PRICES: Record<keyof typeof ASSET_IDS, bigint> = {
  sBTC:  50_000n * 10n ** 8n,
  sETH:   3_000n * 10n ** 8n,
  sAAPL:    200n * 10n ** 8n,
  sTSLA:    250n * 10n ** 8n,
}

export type ContractName = keyof typeof ANVIL
export type AssetSymbol  = keyof typeof ASSET_IDS
TSEOF

echo "Done. Files written to $FRONTEND_CONTRACTS"
