// Per-stage skin pools. The shop and the gacha only ever offer the pool that
// matches the player's current evolution stage — a Lv.0 egg is offered egg
// skins, a tadpole is offered tadpole skins, and so on.
//
// Stages with no artwork yet are simply absent from this map; the UI treats a
// missing pool as "coming soon" rather than erroring or falling back to another
// stage's art.
//
// GENERATED by scripts/import-skins.py — edit that, not this.

import { t } from 'src/locales';

export interface StageSkin {
  id: string;
  name: string;
  stage: number;
  rarity: 'Common' | 'Rare' | 'Epic' | 'Legendary';
  price: number;
  emoji: string;
  image: string;
  /** Contact line as a fraction of image height, measured from the WebP. */
  groundY: number;
}

/** id 以外全是資料；`name` 是顯示字串，住在 catalog。 */
type StageSkinData = Omit<StageSkin, 'name'> & { id: keyof typeof t.pepeStageSkins };

const STAGE_SKINS: Record<number, StageSkinData[]> = {

  0: [
    { id: 's0_candle', stage: 0, rarity: 'Common', price: 150, emoji: '📈', image: '/pepe-skins/stage0/candle.webp', groundY: 0.828 },
    { id: 's0_pepe', stage: 0, rarity: 'Common', price: 150, emoji: '🥚', image: '/pepe-skins/stage0/pepe.webp', groundY: 0.83 },
    { id: 's0_cosmic', stage: 0, rarity: 'Common', price: 150, emoji: '🌌', image: '/pepe-skins/stage0/cosmic.webp', groundY: 0.825 },
    { id: 's0_frog', stage: 0, rarity: 'Common', price: 150, emoji: '🐸', image: '/pepe-skins/stage0/frog.webp', groundY: 0.82 },
    { id: 's0_crystal', stage: 0, rarity: 'Common', price: 150, emoji: '💎', image: '/pepe-skins/stage0/crystal.webp', groundY: 0.83 },
    { id: 's0_crown', stage: 0, rarity: 'Rare', price: 320, emoji: '👑', image: '/pepe-skins/stage0/crown.webp', groundY: 0.831 },
    { id: 's0_hatching', stage: 0, rarity: 'Rare', price: 320, emoji: '🐣', image: '/pepe-skins/stage0/hatching.webp', groundY: 0.833 },
    { id: 's0_rune', stage: 0, rarity: 'Rare', price: 320, emoji: '🔮', image: '/pepe-skins/stage0/rune.webp', groundY: 0.834 },
    { id: 's0_embryo', stage: 0, rarity: 'Epic', price: 650, emoji: '🧬', image: '/pepe-skins/stage0/embryo.webp', groundY: 0.83 },
    { id: 's0_leaf', stage: 0, rarity: 'Legendary', price: 1200, emoji: '🍃', image: '/pepe-skins/stage0/leaf.webp', groundY: 0.828 },
  ],
  1: [
    { id: 's1_sleepy', stage: 1, rarity: 'Common', price: 190, emoji: '😴', image: '/pepe-skins/stage1/sleepy.webp', groundY: 0.825 },
    { id: 's1_crying', stage: 1, rarity: 'Common', price: 190, emoji: '😭', image: '/pepe-skins/stage1/crying.webp', groundY: 0.87 },
    { id: 's1_shades', stage: 1, rarity: 'Common', price: 190, emoji: '😎', image: '/pepe-skins/stage1/shades.webp', groundY: 0.923 },
    { id: 's1_shy', stage: 1, rarity: 'Common', price: 190, emoji: '☺️', image: '/pepe-skins/stage1/shy.webp', groundY: 0.625 },
    { id: 's1_smile', stage: 1, rarity: 'Common', price: 190, emoji: '🙂', image: '/pepe-skins/stage1/smile.webp', groundY: 0.808 },
    { id: 's1_dizzy', stage: 1, rarity: 'Rare', price: 360, emoji: '😵', image: '/pepe-skins/stage1/dizzy.webp', groundY: 0.884 },
    { id: 's1_diver', stage: 1, rarity: 'Rare', price: 360, emoji: '🤿', image: '/pepe-skins/stage1/diver.webp', groundY: 0.827 },
    { id: 's1_cheeky', stage: 1, rarity: 'Rare', price: 360, emoji: '😜', image: '/pepe-skins/stage1/cheeky.webp', groundY: 0.881 },
    { id: 's1_joyful', stage: 1, rarity: 'Epic', price: 690, emoji: '🤩', image: '/pepe-skins/stage1/joyful.webp', groundY: 0.642 },
    { id: 's1_surprised', stage: 1, rarity: 'Legendary', price: 1240, emoji: '😲', image: '/pepe-skins/stage1/surprised.webp', groundY: 0.834 },
  ],
  2: [
    { id: 's2_pacifier', stage: 2, rarity: 'Common', price: 230, emoji: '🍼', image: '/pepe-skins/stage2/pacifier.webp', groundY: 0.842 },
    { id: 's2_bottle', stage: 2, rarity: 'Common', price: 230, emoji: '🥛', image: '/pepe-skins/stage2/bottle.webp', groundY: 0.848 },
    { id: 's2_teddy', stage: 2, rarity: 'Common', price: 230, emoji: '🧸', image: '/pepe-skins/stage2/teddy.webp', groundY: 0.842 },
    { id: 's2_crawling', stage: 2, rarity: 'Common', price: 230, emoji: '👶', image: '/pepe-skins/stage2/crawling.webp', groundY: 0.809 },
    { id: 's2_toy', stage: 2, rarity: 'Common', price: 230, emoji: '🪀', image: '/pepe-skins/stage2/toy.webp', groundY: 0.844 },
    { id: 's2_birthday', stage: 2, rarity: 'Rare', price: 400, emoji: '🎂', image: '/pepe-skins/stage2/birthday.webp', groundY: 0.853 },
    { id: 's2_sleeping', stage: 2, rarity: 'Rare', price: 400, emoji: '💤', image: '/pepe-skins/stage2/sleeping.webp', groundY: 0.842 },
    { id: 's2_cool', stage: 2, rarity: 'Rare', price: 400, emoji: '🕶️', image: '/pepe-skins/stage2/cool.webp', groundY: 0.842 },
    { id: 's2_happy', stage: 2, rarity: 'Epic', price: 730, emoji: '😄', image: '/pepe-skins/stage2/happy.webp', groundY: 0.841 },
    { id: 's2_snack', stage: 2, rarity: 'Legendary', price: 1280, emoji: '🍪', image: '/pepe-skins/stage2/snack.webp', groundY: 0.85 },
  ],
  3: [
    { id: 's3_tasty', stage: 3, rarity: 'Common', price: 270, emoji: '🥤', image: '/pepe-skins/stage3/tasty.webp', groundY: 0.875 },
    { id: 's3_strong', stage: 3, rarity: 'Common', price: 270, emoji: '💪', image: '/pepe-skins/stage3/strong.webp', groundY: 0.87 },
    { id: 's3_awesome', stage: 3, rarity: 'Common', price: 270, emoji: '👍', image: '/pepe-skins/stage3/awesome.webp', groundY: 0.867 },
    { id: 's3_smooth', stage: 3, rarity: 'Common', price: 270, emoji: '🛹', image: '/pepe-skins/stage3/smooth.webp', groundY: 0.873 },
    { id: 's3_handsome', stage: 3, rarity: 'Common', price: 270, emoji: '😏', image: '/pepe-skins/stage3/handsome.webp', groundY: 0.87 },
    { id: 's3_clever', stage: 3, rarity: 'Rare', price: 440, emoji: '🧠', image: '/pepe-skins/stage3/clever.webp', groundY: 0.87 },
    { id: 's3_melodic', stage: 3, rarity: 'Rare', price: 440, emoji: '🎧', image: '/pepe-skins/stage3/melodic.webp', groundY: 0.875 },
    { id: 's3_superb', stage: 3, rarity: 'Rare', price: 440, emoji: '🏅', image: '/pepe-skins/stage3/superb.webp', groundY: 0.875 },
    { id: 's3_cool', stage: 3, rarity: 'Epic', price: 770, emoji: '🕶️', image: '/pepe-skins/stage3/cool.webp', groundY: 0.866 },
    { id: 's3_cheerful', stage: 3, rarity: 'Legendary', price: 1320, emoji: '😆', image: '/pepe-skins/stage3/cheerful.webp', groundY: 0.873 },
  ],
  4: [
    { id: 's4_boss', stage: 4, rarity: 'Common', price: 310, emoji: '🎩', image: '/pepe-skins/stage4/boss.webp', groundY: 0.897 },
    { id: 's4_cyber', stage: 4, rarity: 'Common', price: 310, emoji: '🤖', image: '/pepe-skins/stage4/cyber.webp', groundY: 0.883 },
    { id: 's4_navy', stage: 4, rarity: 'Common', price: 310, emoji: '🌊', image: '/pepe-skins/stage4/navy.webp', groundY: 0.886 },
    { id: 's4_white', stage: 4, rarity: 'Common', price: 310, emoji: '🤍', image: '/pepe-skins/stage4/white.webp', groundY: 0.886 },
    { id: 's4_platinum', stage: 4, rarity: 'Common', price: 310, emoji: '💠', image: '/pepe-skins/stage4/platinum.webp', groundY: 0.883 },
    { id: 's4_amethyst', stage: 4, rarity: 'Rare', price: 480, emoji: '💜', image: '/pepe-skins/stage4/amethyst.webp', groundY: 0.892 },
    { id: 's4_burgundy', stage: 4, rarity: 'Rare', price: 480, emoji: '🍷', image: '/pepe-skins/stage4/burgundy.webp', groundY: 0.884 },
    { id: 's4_champagne', stage: 4, rarity: 'Rare', price: 480, emoji: '🥂', image: '/pepe-skins/stage4/champagne.webp', groundY: 0.884 },
    { id: 's4_leather', stage: 4, rarity: 'Epic', price: 810, emoji: '🧥', image: '/pepe-skins/stage4/leather.webp', groundY: 0.878 },
    { id: 's4_blackgold', stage: 4, rarity: 'Legendary', price: 1360, emoji: '🖤', image: '/pepe-skins/stage4/blackgold.webp', groundY: 0.878 },
  ],
  5: [
    { id: 's5_frost', stage: 5, rarity: 'Common', price: 350, emoji: '🧊', image: '/pepe-skins/stage5/frost.webp', groundY: 0.922 },
    { id: 's5_north', stage: 5, rarity: 'Common', price: 350, emoji: '❄️', image: '/pepe-skins/stage5/north.webp', groundY: 0.873 },
    { id: 's5_dark', stage: 5, rarity: 'Common', price: 350, emoji: '🌑', image: '/pepe-skins/stage5/dark.webp', groundY: 0.867 },
    { id: 's5_forest', stage: 5, rarity: 'Common', price: 350, emoji: '🌳', image: '/pepe-skins/stage5/forest.webp', groundY: 0.916 },
    { id: 's5_europa', stage: 5, rarity: 'Common', price: 350, emoji: '🏰', image: '/pepe-skins/stage5/europa.webp', groundY: 0.897 },
    { id: 's5_pharaoh', stage: 5, rarity: 'Rare', price: 520, emoji: '🏺', image: '/pepe-skins/stage5/pharaoh.webp', groundY: 0.925 },
    { id: 's5_poseidon', stage: 5, rarity: 'Rare', price: 520, emoji: '🔱', image: '/pepe-skins/stage5/poseidon.webp', groundY: 0.863 },
    { id: 's5_divine', stage: 5, rarity: 'Rare', price: 520, emoji: '🕊️', image: '/pepe-skins/stage5/divine.webp', groundY: 0.928 },
    { id: 's5_supreme', stage: 5, rarity: 'Epic', price: 850, emoji: '👑', image: '/pepe-skins/stage5/supreme.webp', groundY: 0.872 },
    { id: 's5_golden', stage: 5, rarity: 'Legendary', price: 1400, emoji: '🥇', image: '/pepe-skins/stage5/golden.webp', groundY: 0.878 },
  ],
  6: [
    { id: 's6_light', stage: 6, rarity: 'Common', price: 390, emoji: '🌟', image: '/pepe-skins/stage6/light.webp', groundY: 0.905 },
    { id: 's6_moon', stage: 6, rarity: 'Common', price: 390, emoji: '🌙', image: '/pepe-skins/stage6/moon.webp', groundY: 0.678 },
    { id: 's6_angel', stage: 6, rarity: 'Common', price: 390, emoji: '👼', image: '/pepe-skins/stage6/angel.webp', groundY: 0.894 },
    { id: 's6_cosmos', stage: 6, rarity: 'Common', price: 390, emoji: '🌌', image: '/pepe-skins/stage6/cosmos.webp', groundY: 0.722 },
    { id: 's6_starry', stage: 6, rarity: 'Common', price: 390, emoji: '✨', image: '/pepe-skins/stage6/starry.webp', groundY: 0.906 },
    { id: 's6_time', stage: 6, rarity: 'Rare', price: 560, emoji: '⏳', image: '/pepe-skins/stage6/time.webp', groundY: 0.686 },
    { id: 's6_sylvan', stage: 6, rarity: 'Rare', price: 560, emoji: '🌲', image: '/pepe-skins/stage6/sylvan.webp', groundY: 0.692 },
    { id: 's6_flame', stage: 6, rarity: 'Rare', price: 560, emoji: '🔥', image: '/pepe-skins/stage6/flame.webp', groundY: 0.722 },
    { id: 's6_almighty', stage: 6, rarity: 'Epic', price: 890, emoji: '⚡', image: '/pepe-skins/stage6/almighty.webp', groundY: 0.648 },
    { id: 's6_thunder', stage: 6, rarity: 'Legendary', price: 1440, emoji: '🌩️', image: '/pepe-skins/stage6/thunder.webp', groundY: 0.717 },
  ],
};

export const PEPE_STAGE_SKINS: Record<number, StageSkin[]> = Object.fromEntries(
  Object.entries(STAGE_SKINS).map(([stage, skins]) => [
    Number(stage),
    skins.map((s) => ({ ...s, name: t.pepeStageSkins[s.id] })),
  ]),
);

/** The pool for a stage, or an empty array when that artwork does not exist yet. */
export function getStageSkins(stage: number): StageSkin[] {
  return PEPE_STAGE_SKINS[stage] || [];
}

/** Every skin across every stage — used to resolve an equipped skin by id. */
export const ALL_STAGE_SKINS: StageSkin[] = Object.values(PEPE_STAGE_SKINS).flat();

/** Resolve an owned skin by its id, whichever stage it came from. */
export function findStageSkin(id: string): StageSkin | undefined {
  return ALL_STAGE_SKINS.find((s) => s.id === id);
}
