// Auto-generated by deploy-anvil.sh — do not edit ANVIL section manually
// Sepolia section updated automatically by deploy-sepolia.sh

export interface ChainAddresses {
  MockUSDC:          string
  MockOracle:        string
  TraderStake:       string
  InsuranceVault:    string
  FeeRouter:         string
  PerpetualExchange: string
  StrategyRegistry:  string
  CopyTracker:       string
  MockSwapRouter:    string
}

// ── Anvil local (chainId 31337) ───────────────────────────────────────────────
const ANVIL: ChainAddresses = {
  MockUSDC:          "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
  MockOracle:        "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
  TraderStake:       "0x0000000000000000000000000000000000000000",
  InsuranceVault:    "0x0000000000000000000000000000000000000000",
  FeeRouter:         "0x0000000000000000000000000000000000000000",
  PerpetualExchange: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
  StrategyRegistry:  "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
  CopyTracker:       "0x68B1D87F95878fE05B998F19b66F4baba5De1aed",
  MockSwapRouter:    "0x0000000000000000000000000000000000000000",
}

// ── Sepolia testnet (chainId 11155111) ────────────────────────────────────────
const SEPOLIA: ChainAddresses = {
  MockUSDC:          "0x82c94AAE3F50F2eE31241B986366BC929b774f7a",
  MockOracle:        "0x3f1E53C64bc644D07b8FA76baC8aEE33b96194d8",
  TraderStake:       "0x2cBB4310Dfc62A591975f71c818EF4E3f655Bc1d",
  InsuranceVault:    "0xE40ABfbDb4B70A3788faF0E6A04e10C4204A6eB3",
  FeeRouter:         "0x0FfA7f279fED4E19b3018A4461A8F387aA6c16C2",
  PerpetualExchange: "0x4cC711AEa7c6D7E19e99676b51b7A69ee08c31Eb",
  StrategyRegistry:  "0xe362dE5b06e98D4c5292209EEc965aC842d36c75",
  CopyTracker:       "0x191b8D2F561F977c8bF31e40a0E03fafd7c1E421",
  MockSwapRouter:    "0xcDcC229A7C33FafCc5C963308eC08934F4F86985",
}

const CHAIN_MAP: Record<number, ChainAddresses> = {
  31337:    ANVIL,
  11155111: SEPOLIA,
}

export const getAddresses = (chainId: number | null): ChainAddresses | null =>
  chainId === null ? null : (CHAIN_MAP[chainId] ?? null)

export const CHAIN_NAMES: Record<number, string> = {
  31337:    'Anvil Local',
  11155111: 'Sepolia',
}


// keccak256 of symbol string — matches Deploy.s.sol and on-chain IDs
export const ASSET_IDS = {
  sBTC:  "0x6587d61b59ac1e9c9f12c71f220fb1b1740d054e81277d4466a0d348e0e266e1" as `0x${string}`,
  sETH:  "0x83e22e1d95f2093dd401ec5cba75bcd950cd90282356f086011849e4fbaad8a9"  as `0x${string}`,
  sAAPL: "0xeed17252f75eebef59a2839f0991464677fec970326e35128ddaf7f3acfb7220"  as `0x${string}`,
  sTSLA: "0xd3cea6476633c192bfd36c9af4a9d0ee6e1863484325ee0f546a36393d1df1e9"  as `0x${string}`,
} as const

// Initial oracle prices (8-decimal, same as MockOracle storage)
export const INITIAL_PRICES: Record<keyof typeof ASSET_IDS, bigint> = {
  sBTC:  50_000n * 10n ** 8n,
  sETH:   3_000n * 10n ** 8n,
  sAAPL:    200n * 10n ** 8n,
  sTSLA:    250n * 10n ** 8n,
}

export type ContractName = keyof typeof ANVIL
export type AssetSymbol  = keyof typeof ASSET_IDS
