// Auto-generated by deploy-anvil.sh — do not edit ANVIL section manually
// Sepolia section updated automatically by deploy-sepolia.sh

export interface ChainAddresses {
  MockUSDC:          string
  MockOracle:        string
  TraderStake:       string
  FeeRouter:         string
  PerpetualExchange: string
  StrategyRegistry:  string
  CopyTracker:       string
}

// ── Anvil local (chainId 31337) ───────────────────────────────────────────────
const ANVIL: ChainAddresses = {
  MockUSDC:          "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
  MockOracle:        "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
  TraderStake:       "0x0000000000000000000000000000000000000000",
  FeeRouter:         "0x0000000000000000000000000000000000000000",
  PerpetualExchange: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
  StrategyRegistry:  "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
  CopyTracker:       "0x68B1D87F95878fE05B998F19b66F4baba5De1aed",
}

// ── Sepolia testnet (chainId 11155111) ────────────────────────────────────────
const SEPOLIA: ChainAddresses = {
  MockUSDC:          "0x7A7D35106B79919A48494BD5c827350bC179ACcF",
  MockOracle:        "0x18c35cb3D3DdC522D0b7996e01d4a5C8b9cf16f4",
  TraderStake:       "0x0000000000000000000000000000000000000000",
  FeeRouter:         "0x0000000000000000000000000000000000000000",
  PerpetualExchange: "0x00f6cf0113399a7A451c7f85fe094a28092d3e0c",
  StrategyRegistry:  "0xEf75ECA6514cE96B18382E921aC6190a0cF8c072",
  CopyTracker:       "0x54e8C43f9Eb151Bb8DD6e61d16a969C4D0e73915",
}

const CHAIN_MAP: Record<number, ChainAddresses> = {
  31337:    ANVIL,
  11155111: SEPOLIA,
}

export const getAddresses = (chainId: number | null): ChainAddresses | null =>
  chainId === null ? null : (CHAIN_MAP[chainId] ?? null)

export const CHAIN_NAMES: Record<number, string> = {
  31337:    'Anvil Local',
  11155111: 'Sepolia',
}


// keccak256 of symbol string — matches Deploy.s.sol and on-chain IDs
export const ASSET_IDS = {
  sBTC:  "0x6587d61b59ac1e9c9f12c71f220fb1b1740d054e81277d4466a0d348e0e266e1" as `0x${string}`,
  sETH:  "0x83e22e1d95f2093dd401ec5cba75bcd950cd90282356f086011849e4fbaad8a9"  as `0x${string}`,
  sAAPL: "0xeed17252f75eebef59a2839f0991464677fec970326e35128ddaf7f3acfb7220"  as `0x${string}`,
  sTSLA: "0xd3cea6476633c192bfd36c9af4a9d0ee6e1863484325ee0f546a36393d1df1e9"  as `0x${string}`,
} as const

// Initial oracle prices (8-decimal, same as MockOracle storage)
export const INITIAL_PRICES: Record<keyof typeof ASSET_IDS, bigint> = {
  sBTC:  50_000n * 10n ** 8n,
  sETH:   3_000n * 10n ** 8n,
  sAAPL:    200n * 10n ** 8n,
  sTSLA:    250n * 10n ** 8n,
}

export type ContractName = keyof typeof ANVIL
export type AssetSymbol  = keyof typeof ASSET_IDS
