// SessionCredentialAnchor (contracts/src/SessionCredentialAnchor.sol): the session user
// anchors the EIP-712 hash of a v3 AgentDelegationCredential so third parties (x402 KYA in
// signal-api) can check that the credential is the one the session owner stands behind.
// docs/SSI_AGENT_DELEGATION.md.
//
// Kept out of addresses.ts on purpose: that file is regenerated by the deploy scripts and
// inlined into the signal-api Vercel bundle (bundle:check fingerprint). Deploy with
// contracts/script/DeploySessionCredentialAnchor.s.sol, then fill the table below — or set
// VITE_SESSION_ANCHOR_ADDRESS for a local run (it wins over the table). Not deployed on a
// chain = the page still issues v3 credentials, it just cannot anchor them.
import type { Signer, BrowserProvider } from 'ethers'

import { Contract, isAddress } from 'ethers'

const ZERO = '0x0000000000000000000000000000000000000000'

export const SESSION_ANCHOR_ADDRESS: Record<number, string> = {
  31337: ZERO, // Anvil: scripts/poc/agent-delegation-demo deploys a fresh one each run
  84532: ZERO, // Base Sepolia: not deployed yet (owner action)
}

export const SESSION_ANCHOR_ABI = [
  'function anchor(uint256 sessionId, bytes32 credentialHash)',
  'function unanchor(uint256 sessionId, bytes32 credentialHash)',
  'function isAnchored(uint256 sessionId, bytes32 credentialHash) view returns (bool)',
  'function anchorStatus(uint256 sessionId, bytes32 credentialHash) view returns (bool recorded, bool sessionLive, address user, uint256 since)',
  'function currentCredential(uint256 sessionId) view returns (bytes32)',
  'event CredentialAnchored(uint256 indexed sessionId, address indexed user, bytes32 indexed credentialHash, bytes32 previousHash, uint256 version)',
] as const

/** Resolve the anchor for a chain; `envOverride` defaults to VITE_SESSION_ANCHOR_ADDRESS. */
export function getSessionAnchorAddress(
  chainId: number | null,
  envOverride: string | undefined = import.meta.env.VITE_SESSION_ANCHOR_ADDRESS as string | undefined,
): string {
  const env = envOverride?.trim()
  if (env && isAddress(env) && env.toLowerCase() !== ZERO) return env
  if (chainId === null) return ZERO
  return SESSION_ANCHOR_ADDRESS[chainId] ?? ZERO
}

export function isSessionAnchorDeployed(chainId: number | null, envOverride?: string): boolean {
  return getSessionAnchorAddress(chainId, envOverride) !== ZERO
}

export function getSessionAnchor(runner: Signer | BrowserProvider | null, chainId: number | null): Contract | null {
  if (!runner) return null
  const addr = getSessionAnchorAddress(chainId)
  if (addr === ZERO) return null
  return new Contract(addr, SESSION_ANCHOR_ABI, runner)
}
