// SessionCredentialAnchor (contracts/src/SessionCredentialAnchor.sol): the session user
// anchors the EIP-712 hash of a v3 AgentDelegationCredential so third parties (x402 KYA in
// signal-api) can check that the credential is the one the session owner stands behind.
// docs/SSI_AGENT_DELEGATION.md.
//
// Kept out of addresses.ts on purpose: that file is regenerated by the deploy scripts and
// inlined into the signal-api Vercel bundle (bundle:check fingerprint). Deploy with
// contracts/script/DeploySessionCredentialAnchor.s.sol, then fill the table below — or set
// VITE_SESSION_ANCHOR_ADDRESS for a local run. The override applies to ONE chain only
// (VITE_SESSION_ANCHOR_CHAIN_ID, default 31337): an anvil address must never be used on a
// wallet that switched to Base Sepolia, where it may be an EOA and an anchor() "succeeds"
// without anchoring anything. Not deployed on a chain = the page still issues v3
// credentials, it just cannot anchor them.
import type { Signer, BrowserProvider } from 'ethers'

import { Contract, getAddress, isAddress } from 'ethers'

const ZERO = '0x0000000000000000000000000000000000000000'

export const SESSION_ANCHOR_ADDRESS: Record<number, string> = {
  31337: ZERO, // Anvil: scripts/poc/agent-delegation-demo deploys a fresh one each run
  84532: ZERO, // Base Sepolia: not deployed yet (owner action)
}

export const SESSION_ANCHOR_ABI = [
  'function anchor(uint256 sessionId, bytes32 credentialHash)',
  'function unanchor(uint256 sessionId, bytes32 credentialHash)',
  'function isAnchored(uint256 sessionId, bytes32 credentialHash) view returns (bool)',
  'function anchorStatus(uint256 sessionId, bytes32 credentialHash) view returns (bool recorded, bool sessionLive, address user, uint256 since)',
  'function currentCredential(uint256 sessionId) view returns (bytes32)',
  'function sessionManager() view returns (address)',
  'event CredentialAnchored(uint256 indexed sessionId, address indexed user, bytes32 indexed credentialHash, bytes32 previousHash, uint256 version)',
] as const

/** The chain VITE_SESSION_ANCHOR_ADDRESS applies to (VITE_SESSION_ANCHOR_CHAIN_ID, default 31337). */
export function sessionAnchorOverrideChainId(
  raw: string | undefined = import.meta.env.VITE_SESSION_ANCHOR_CHAIN_ID as string | undefined,
): number {
  const n = Number(raw?.trim())
  return raw?.trim() && Number.isSafeInteger(n) && n > 0 ? n : 31337
}

/**
 * Resolve the anchor for a chain; `envOverride` defaults to VITE_SESSION_ANCHOR_ADDRESS and only
 * applies on `overrideChainId` (default: sessionAnchorOverrideChainId()).
 */
export function getSessionAnchorAddress(
  chainId: number | null,
  envOverride: string | undefined = import.meta.env.VITE_SESSION_ANCHOR_ADDRESS as string | undefined,
  overrideChainId: number = sessionAnchorOverrideChainId(),
): string {
  if (chainId === null) return ZERO
  const env = envOverride?.trim()
  if (chainId === overrideChainId && env && isAddress(env) && env.toLowerCase() !== ZERO) return env
  return SESSION_ANCHOR_ADDRESS[chainId] ?? ZERO
}

export function isSessionAnchorDeployed(chainId: number | null, envOverride?: string): boolean {
  return getSessionAnchorAddress(chainId, envOverride) !== ZERO
}

export function getSessionAnchor(runner: Signer | BrowserProvider | null, chainId: number | null): Contract | null {
  if (!runner) return null
  const addr = getSessionAnchorAddress(chainId)
  if (addr === ZERO) return null
  return new Contract(addr, SESSION_ANCHOR_ABI, runner)
}

/**
 * Before sending anchor()/unanchor(): the address must hold code (a call to an EOA "succeeds"
 * and anchors nothing) and be bound to the session manager the credential names (anchoring
 * rights come from that manager's sessions). Returns an English error code or null.
 */
export async function sessionAnchorProblem(
  anchor: Pick<Contract, 'getAddress' | 'sessionManager'> & { runner: { provider?: { getCode(a: string): Promise<string> } | null } | null },
  expectedSessionManager: string,
): Promise<'anchor_no_code' | 'anchor_wrong_manager' | 'anchor_unreadable' | null> {
  try {
    const provider = anchor.runner?.provider
    if (!provider) return 'anchor_unreadable'
    const code = await provider.getCode(await anchor.getAddress())
    if (!code || code === '0x') return 'anchor_no_code'
    const bound = String(await anchor.sessionManager())
    return getAddress(bound) === getAddress(expectedSessionManager) ? null : 'anchor_wrong_manager'
  } catch {
    return 'anchor_unreadable'
  }
}
