#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# ==========================================================================
#  #129 主鏈硬化版金庫 ＋ 碳定價連鎖重部署 wizard （中文 · 全程對 Base Sepolia 84532）
#
#  它做什麼：一步一步跑完 docs/DEPLOY_129_CUTOVER.md 的六個 phase（A 硬化版金庫、
#  B 見證登記所、C 碳定價交易所鏈、D 獎勵發放、E 接金庫、F 逐項驗證），加上開放
#  鑄造、回填 addresses.ts / agent/.env、demo 收尾。每個「送鏈」動作前都會停下來
#  確認。可隨時 Ctrl-C；重跑時把 scratch 檔 source 回來就接續（見結尾）。
#
#  在哪跑：WSL，倉庫根目錄底下：   bash scripts/deploy-129.sh
#  先決：
#    - #128（PR #141）已合併，或至少 checkout feat/129-… 分支（要 AssetVaultV2_4.sol）
#    - foundry（forge/cast）、jq、awk
#    - export PRIVATE_KEY=0x…              （合約現任 owner，見下）
#    - export BASE_SEPOLIA_RPC_URL=…
#    - export BASESCAN_API_KEY=…           （選用，開 --verify）
#    - export ADMIN_ADDRESS / KEEPER_ADDRESS / GUARDIAN_ADDRESS = 三把不同的 key
#      （沒設會退回部署者 —— GuardedOracle 的偏離上限 / freeze / pause 等於零）
#
#  金鑰：合約現任 owner 是 0x27C21324D101e867E0634bf2ebe3F9Dcf3ACA585
#        （2026-08-07 輪替，見 docs/KEY_ROTATION_20260807.md）。私鑰不在 git 裡；
#        跟執行輪替的組員 / 團隊密碼管理器要。
#        ⚠ contracts/.env.example 的 PRIVATE_KEY 是 Anvil 假金鑰，不要用。
#        該錢包要有 Base Sepolia ETH 付 gas（約 25–35 筆交易）。
#
#  ⚠ 這個 wizard 與它呼叫的 forge 腳本對 Base Sepolia fork 模擬過（含 phase C 的
#    schema 閘），但沒對鏈實際 broadcast 過。每個 forge 步驟都對應
#    docs/DEPLOY_129_CUTOVER.md 的手動指令 —— 卡住就翻那份、手動跑。
#    保護不可逆步驟的是 Stage 5 的 dry-run 閘（純讀取）+ Redeploy129Exchange 自己
#    的 schema/seed 前置檢查。
#
#  forge 廣播都帶 --slow（每筆等 receipt，nonce 嚴格遞增 —— Base 對 7702-delegated
#  帳號拒絕 gapped nonce）。
# ==========================================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="$REPO_ROOT/contracts"
ADDR_TS="$REPO_ROOT/frontend/src/contracts/addresses.ts"
SCRATCH="$REPO_ROOT/scripts/.deploy-129-addresses.env"   # gitignored
CHAIN=84532
RPC="${BASE_SEPOLIA_RPC_URL:-}"
FORGE_VERIFY=""
[[ -n "${BASESCAN_API_KEY:-}" ]] && FORGE_VERIFY="--verify --etherscan-api-key $BASESCAN_API_KEY"

# Base Sepolia pieces that stay put (see DEPLOY_129 §0.4).
USDC=0x69fd695Bc7C3aFdb35ABA35cD6890C506400b035
MOCKORACLE=0xeD90c4F3B48213888870C1FC8486921Cb0990Aa3
FEE_ROUTER=0x00f6cf0113399a7A451c7f85fe094a28092d3e0c
INS_VAULT=0xB364E2e3e1e7a2b033eF03a4ACceF42066F3D812
TRADER_STK=0x01aEB530bcFc69f036309ffe55acc7eA6C5a28Fe
OLD_EXCHANGE=0xfAEf549C687C37064cEaB5728989a839B08955cf
OLD_SESSION_MANAGER=0x5Ebcc64C712C5a26119789dCbD0753981dc518E8
EXPECTED_OWNER=0x27C21324D101e867E0634bf2ebe3F9Dcf3ACA585
SYMS=(sBTC sETH sAAPL sTSLA sGOLD sBOND sNVDA sMSFT sGOOGL sICLN sESGU)

# ── helpers (this wizard's own, beyond the library) ──────────────────────

die()  { printf '\n  %s✖ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
run()  { printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"; "$@"; }

remember() { printf 'export %s=%s\n' "$1" "$2" >> "$SCRATCH"; ok "記下 $1=$2"; }

# grab the last 0x-address on any line containing $1, from log file $2
grab_addr() { grep -E "$1" "$2" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1 || true; }

# cast call, printing the command
cc() { printf '  %s· cast call %s "%s" %s%s\n' "$DIM" "$1" "$2" "${*:3}" "$RESET"; cast call "$1" "$2" "${@:3}" --rpc-url "$RPC"; }

# cast send, confirm before sending; PRIV overridable for non-owner keys
cs() {
  local priv="${PRIV:-$PRIVATE_KEY}"
  printf '  %s將送出：%s cast send %s "%s" %s\n' "$YELLOW" "$RESET" "$1" "$2" "${*:3}"
  confirm "送出這筆交易？" || { warn "跳過"; return 1; }
  cast send "$1" "$2" "${@:3}" --private-key "$priv" --rpc-url "$RPC"
}

# patch one KEY: "0x…" line inside addresses.ts's BASE_SEPOLIA ChainAddresses block
patch_addr() {
  local key="$1" val="$2"
  awk -v k="$key" -v v="$val" '
    /^const BASE_SEPOLIA/ { inblk=1 }
    inblk && /^\}/        { inblk=0 }
    inblk && $0 ~ ("^[[:space:]]*" k ":[[:space:]]*\"0x") {
      sub(/"0x[0-9a-fA-F]+"/, "\"" v "\""); print; next
    }
    { print }
  ' "$ADDR_TS" > "$ADDR_TS.tmp" && mv "$ADDR_TS.tmp" "$ADDR_TS"
  ok "addresses.ts BASE_SEPOLIA.$key → $val"
}

# patch one KEY: "0x…" line inside V2_STACK[84532] (scoped to the V2_STACK Record).
# The Record ends with a bare `}` at column 0; its TYPE closes with `}> = {`,
# which we must NOT treat as the end — hence the `^\}$` anchor.
patch_v2stack() {
  local key="$1" val="$2"
  awk -v k="$key" -v v="$val" '
    /^export const V2_STACK/  { instack=1 }
    instack && /^\}$/         { instack=0 }
    instack && /^  84532: \{/ { inblk=1 }
    inblk && /^  \},/         { inblk=0 }
    inblk && $0 ~ ("^[[:space:]]*" k ":[[:space:]]*\"0x") {
      sub(/"0x[0-9a-fA-F]+"/, "\"" v "\""); print; next
    }
    { print }
  ' "$ADDR_TS" > "$ADDR_TS.tmp" && mv "$ADDR_TS.tmp" "$ADDR_TS"
  ok "addresses.ts V2_STACK[84532].$key → $val"
}

forge_run() {   # forge_run <ScriptFile:Contract> <logfile> [extra forge args...]
  local target="$1" logf="$2"; shift 2
  ( cd "$CONTRACTS" && forge script "script/$target" --rpc-url "$RPC" "$@" -vvv ) 2>&1 | tee "$logf"
  return "${PIPESTATUS[0]}"
}

# ==========================================================================

banner "#129 主鏈硬化版金庫 ＋ 碳定價連鎖重部署"

# ── Stage 1 · 環境檢查 ────────────────────────────────────────────────────
stage "環境檢查"
say "確認工具、金鑰、餘額、分支、角色分離。"
for c in forge cast jq git awk; do command -v "$c" >/dev/null || die "找不到 $c。foundry 在 WSL 常沒進非互動 PATH —— 見 docs/agents/environment.md，或 export PATH=\$HOME/.foundry/bin:\$PATH"; done
[[ -n "${PRIVATE_KEY:-}" ]] || die "沒設 PRIVATE_KEY。現任 owner 是 $EXPECTED_OWNER（key 在密碼管理器 / 組員手上，見 docs/KEY_ROTATION_20260807.md）。"
[[ -n "$RPC" ]] || die "沒設 BASE_SEPOLIA_RPC_URL"
[[ -f "$CONTRACTS/src/v2/AssetVaultV2_4.sol" ]] || die "找不到 contracts/src/v2/AssetVaultV2_4.sol —— 先合併 #128（PR #141）或 checkout feat/129-… 分支。"
DEPLOYER="$(cast wallet address --private-key "$PRIVATE_KEY")" || die "PRIVATE_KEY 格式不對"
ok "部署者地址：$DEPLOYER"
if [[ "${DEPLOYER,,}" == "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" ]]; then
  die "這是 Anvil 測試帳號 #0（contracts/.env.example 預設值）—— 不擁有任何 Base Sepolia 合約。"
fi
CID="$(cast chain-id --rpc-url "$RPC")"; [[ "$CID" == "$CHAIN" ]] || die "RPC 指向 chain $CID，不是 Base Sepolia（$CHAIN）"
BAL_ETH="$(cast from-wei "$(cast balance "$DEPLOYER" --rpc-url "$RPC")")"
say "ETH 餘額：$BAL_ETH"
awk -v b="$BAL_ETH" 'BEGIN{ if (b+0 < 0.05) exit 1 }' || warn "餘額偏低，這輪約 25–35 筆交易 —— 水龍頭：https://docs.base.org/chain/network-faucets"
OWNER_EX="$(cast call "$OLD_EXCHANGE" 'owner()(address)' --rpc-url "$RPC")"
if [[ "${OWNER_EX,,}" == "${DEPLOYER,,}" ]]; then
  ok "你這把金鑰是現行 PerpetualExchange 的 owner"
else
  warn "現行 PerpetualExchange owner 是 $OWNER_EX，不是你（$DEPLOYER）。"
  warn "phase C 的 setExchange / setCopyTracker / setRwaAsset 會 revert。"
  confirm "還是要繼續（不建議）" || die "換成 owner 金鑰再來"
fi
# 角色分離
ADMIN_ADDRESS="${ADMIN_ADDRESS:-$DEPLOYER}"
KEEPER_ADDRESS="${KEEPER_ADDRESS:-$DEPLOYER}"
GUARDIAN_ADDRESS="${GUARDIAN_ADDRESS:-$DEPLOYER}"
export ADMIN_ADDRESS KEEPER_ADDRESS GUARDIAN_ADDRESS
say "角色：admin=$ADMIN_ADDRESS  keeper=$KEEPER_ADDRESS  guardian=$GUARDIAN_ADDRESS"
if [[ "${ADMIN_ADDRESS,,}" == "${KEEPER_ADDRESS,,}" || "${ADMIN_ADDRESS,,}" == "${GUARDIAN_ADDRESS,,}" || "${KEEPER_ADDRESS,,}" == "${GUARDIAN_ADDRESS,,}" ]]; then
  warn "ADMIN / KEEPER / GUARDIAN 不是三把不同的 key —— GuardedOracle 的偏離上限、freeze、pause 等於零。"
  warn "這配置只給本機測試。正式部署前 export 三個不同地址。"
  confirm "仍要以未分離的角色繼續" || die "設好 ADMIN_ADDRESS / KEEPER_ADDRESS / GUARDIAN_ADDRESS 再來"
fi
# 續跑
if [[ -s "$SCRATCH" ]]; then
  say "偵測到 scratch 檔：$SCRATCH"; cat "$SCRATCH"
  if confirm "接續執行 —— source 回既有位址（跳過已完成的 phase）？"; then
    # shellcheck disable=SC1090
    source "$SCRATCH"; ok "已載入既有位址"
  else
    : > "$SCRATCH"; printf '# #129 部署 — 抓到的新位址（可 source 回來接續）\n' >> "$SCRATCH"
  fi
else
  : > "$SCRATCH"; printf '# #129 部署 — 抓到的新位址（可 source 回來接續）\n' >> "$SCRATCH"
fi
pause "檢查通過。Enter 繼續"

# ── Stage 2 · 編譯 ───────────────────────────────────────────────────────
stage "編譯合約"
say "forge build —— 產生 ABI（等一下複製到前端）並驗證六個腳本可編譯。"
run bash -c "cd '$CONTRACTS' && forge build" || die "forge build 失敗 —— 先修編譯錯誤"
ok "編譯通過"
pause "Enter 繼續"

# ── Stage 3 · Phase A：硬化版金庫 ───────────────────────────────────────
stage "Phase A — GuardedOracle + AssetVaultV2_4 proxy + 11 顆 token"
if [[ -n "${VAULT_PROXY_129:-}" && -n "${GUARDED_ORACLE_129:-}" ]]; then
  ok "已完成（VAULT_PROXY_129=$VAULT_PROXY_129）—— 跳過"; pause "Enter 繼續"
else
say "不動任何既有合約。價格從現行 MockOracle 複製,GuardedOracle 起始就同步。"
confirm "廣播 phase A？" || die "已中止"
export MOCKUSDC_ADDR="$USDC" MOCKORACLE_ADDR="$MOCKORACLE"
LA="$REPO_ROOT/scripts/.log-129-a.txt"
forge_run "DeployHardenedVault129.s.sol:DeployHardenedVault129" "$LA" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "phase A 失敗 —— 看 $LA，別重跑整段（會 fork）；可用 cast 補完 onlyOwner setter"
GUARDED_ORACLE_129="$(grab_addr 'GUARDED_ORACLE_129=' "$LA")"; [[ -n "$GUARDED_ORACLE_129" ]] || die "撈不到 GuardedOracle 位址,看 $LA"
VAULT_PROXY_129="$(grab_addr 'VAULT_PROXY_129=' "$LA")";       [[ -n "$VAULT_PROXY_129" ]] || die "撈不到金庫 proxy 位址"
export GUARDED_ORACLE_129 VAULT_PROXY_129
remember GUARDED_ORACLE_129 "$GUARDED_ORACLE_129"
remember VAULT_PROXY_129 "$VAULT_PROXY_129"
# 11 顆 token
: > "$REPO_ROOT/scripts/.tokens-129.txt"
for s in "${SYMS[@]}"; do
  t="$(grep -E "^\s+$s 0x[0-9a-fA-F]{40}$" "$LA" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1 || true)"
  [[ -n "$t" ]] || warn "撈不到 $s 的 token 位址（看 $LA）"
  printf '%s %s\n' "$s" "$t" >> "$REPO_ROOT/scripts/.tokens-129.txt"
done
say "11 顆 token（也存在 scripts/.tokens-129.txt）："; cat "$REPO_ROOT/scripts/.tokens-129.txt"
say "驗證："
cc "$VAULT_PROXY_129" 'version()(string)';                                              note "期望 2.4.0"
cc "$VAULT_PROXY_129" 'oracle()(address)';                                              note "期望 $GUARDED_ORACLE_129"
cc "$VAULT_PROXY_129" 'esgRegistry()(address)';                                         note "期望 0x0（phase E 才接）"
cc "$VAULT_PROXY_129" 'mintFeeBpsForAsset(bytes32)(uint256)' "$(cast keccak sMSFT)";    note "期望 100（fail-closed,還沒接登記所）"
warn "phase E 之前不要開放鑄造 / 設 cap —— 現在每檔都算最保守級。"
pause "Enter 繼續"
fi

# ── Stage 4 · Phase B：見證登記所 + 見證 11 檔 ─────────────────────────
stage "Phase B — ESGRegistryV2 + SustainabilityBadge + 見證 11 檔（帶 tier/basis）"
if [[ -n "${ESG_REGISTRY_V2:-}" && -n "${SUSTAINABILITY_BADGE:-}" ]]; then
  ok "已完成（ESG_REGISTRY_V2=$ESG_REGISTRY_V2）—— 跳過"; pause "Enter 繼續"
else
say "見證資料在腳本 _assets() 表,對齊 docs/data/carbon-intensity.md 與 assetMeta.ts。"
say "營收基準寫強度且 tier 須 == tierOf(強度)；絕對/質性基準強度 0、tier 直接指定。"
say "每筆帶 sourceHash = keccak256(來源網址 + 擷取日期)。"
if confirm "要布置多見證者（demo 用『三家機構意見不同』)？設 ATTESTOR_2 / ATTESTOR_3 兩把 EOA。"; then
  ask ATTESTOR_2 "ATTESTOR_2 地址（Enter 跳過）"; ask ATTESTOR_3 "ATTESTOR_3 地址（Enter 跳過）"
  [[ -n "${ATTESTOR_2:-}" ]] && export ATTESTOR_2
  [[ -n "${ATTESTOR_3:-}" ]] && export ATTESTOR_3
  warn "額外 attestor 必須各自用自己的 key 再跑一次 Deploy102CarbonRegistry（部署者這次先授它們 ATTESTOR_ROLE）。"
  warn "誠實揭露：那些 key 都是團隊持有 —— 畫面與文件都要這樣寫（#129 story 12）。"
fi
confirm "廣播 phase B？" || die "已中止"
LB="$REPO_ROOT/scripts/.log-129-b.txt"
forge_run "Deploy102CarbonRegistry.s.sol:Deploy102CarbonRegistry" "$LB" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "phase B 失敗 —— 看 $LB"
ESG_REGISTRY_V2="$(grab_addr 'ESGRegistryV2' "$LB")";           [[ -n "$ESG_REGISTRY_V2" ]] || die "撈不到 ESGRegistryV2 位址,看 $LB"
SUSTAINABILITY_BADGE="$(grab_addr 'SustainabilityBadge' "$LB")"; [[ -n "$SUSTAINABILITY_BADGE" ]] || die "撈不到 SustainabilityBadge 位址"
export ESG_REGISTRY_V2 SUSTAINABILITY_BADGE
remember ESG_REGISTRY_V2 "$ESG_REGISTRY_V2"
remember SUSTAINABILITY_BADGE "$SUSTAINABILITY_BADGE"
say "驗證見證（第一個回傳值是 tier：1=Low 2=Mid 3=High；最後一個 bool 要 true）："
for s in sMSFT sNVDA sGOLD sESGU; do
  cc "$ESG_REGISTRY_V2" 'medianCarbonTier(bytes32)(uint8,uint256,uint256,bool)' "$(cast keccak "$s")"
done
note "期望 sMSFT=3 · sNVDA=1 · sGOLD=3 · sESGU=2"
pause "Enter 繼續"
fi

# ── Stage 5 · 清空檢查（dry-run，不送鏈）────────────────────────────────
stage "清空檢查 —— 現行 exchange 還有幾個未平倉部位"
say "純讀取。Redeploy129Exchange 開頭會先驗 ESG_REGISTRY_V2 的 schema + seed —— 指錯或沒 seed 會在這裡 revert。"
LD="$REPO_ROOT/scripts/.log-129-dryrun.txt"
export DRY_RUN=true
forge_run "Redeploy129Exchange.s.sol:Redeploy129Exchange" "$LD" || { unset DRY_RUN; die "dry-run 失敗（多半是 ESG_REGISTRY_V2 不對）,看 $LD"; }
unset DRY_RUN
if grep -q "0 open positions on the old exchange" "$LD"; then
  ok "現行 exchange 0 未平倉 —— 可以切換"
else
  OPENCNT="$(grep -oiE 'open positions[[:space:]:]+[0-9]+' "$LD" | grep -oE '[0-9]+' | tail -1)"
  warn "現行 exchange 還有 ${OPENCNT:-一些} 個未平倉部位（上方 survey 有 id / owner）。"
  say  "每個 owner 自己平倉 + 提保證金,清到 0,再重跑本 wizard（會從 $SCRATCH 接續）："
  say  "  cast send $OLD_EXCHANGE 'closePosition(uint256)' <id>     --private-key <owner_key> --rpc-url \$BASE_SEPOLIA_RPC_URL"
  say  "  cast send $OLD_EXCHANGE 'withdrawMargin(uint256)' <amount> --private-key <owner_key> --rpc-url \$BASE_SEPOLIA_RPC_URL"
  warn "帶著未平倉切換 → phase C 第 5 步之後那些部位在舊 exchange 上 bailout 會 revert,平不掉也清算不了。"
  confirm "我了解風險,仍要帶著這 ${OPENCNT:-?} 個未平倉部位繼續" || die "先清空未平倉部位再重跑"
  warn "已選擇帶著未平倉部位繼續。"
fi
pause "Enter 進入不可逆的部署階段"

# ── Stage 6 · Phase C：碳定價連鎖重部署（不可逆點）─────────────────────
stage "Phase C — PerpetualExchange + StrategyRegistry + CopyTracker + AgentSessionManager + 重接線"
if [[ -n "${EXCHANGE_NEW:-}" ]]; then
  ok "已完成（EXCHANGE_NEW=$EXCHANGE_NEW）—— 跳過"; pause "Enter 繼續"
else
warn "最後兩個呼叫（InsuranceVault / FeeRouter.setExchange）之後,舊 exchange 上虧損部位就平不掉了。"
warn "確定現行 exchange 已清空、前面兩天緩衝還在。"
confirm "廣播 phase C？" || die "已中止（什麼都沒送）"
LC="$REPO_ROOT/scripts/.log-129-c.txt"
forge_run "Redeploy129Exchange.s.sol:Redeploy129Exchange" "$LC" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "phase C 跑到一半失敗 —— 看 $LC 與 contracts/broadcast/Redeploy129Exchange.s.sol/$CHAIN/run-latest.json。別重跑整段;用 cast 補完剩下的 onlyOwner setter。"
EXCHANGE_NEW="$(grab_addr 'PerpetualExchange_NEW' "$LC")"
STRATEGY_REGISTRY_NEW="$(grab_addr 'StrategyRegistry_NEW' "$LC")"
COPYTRACKER_NEW="$(grab_addr 'CopyTracker_NEW' "$LC")"
SESSION_MANAGER_NEW="$(grab_addr 'AgentSessionManager_NEW' "$LC")"
for v in EXCHANGE_NEW STRATEGY_REGISTRY_NEW COPYTRACKER_NEW SESSION_MANAGER_NEW; do
  [[ -n "${!v}" ]] || die "撈不到 $v,看 $LC"
done
export EXCHANGE_NEW STRATEGY_REGISTRY_NEW COPYTRACKER_NEW SESSION_MANAGER_NEW
remember EXCHANGE_NEW "$EXCHANGE_NEW"
remember STRATEGY_REGISTRY_NEW "$STRATEGY_REGISTRY_NEW"
remember COPYTRACKER_NEW "$COPYTRACKER_NEW"
remember SESSION_MANAGER_NEW "$SESSION_MANAGER_NEW"
ok "四合約已上鏈（腳本結尾的 require 全過 = 接線正確）"
pause "Enter 繼續"
fi

# ── Stage 7 · Phase D：獎勵發放 ─────────────────────────────────────────
stage "Phase D — EsgRewardDistributor（發 SustainabilityBadge,exchange 之後才能部署）"
if [[ -n "${REWARD_DISTRIBUTOR_NEW:-}" ]]; then
  ok "已完成（$REWARD_DISTRIBUTOR_NEW）—— 跳過"; pause "Enter 繼續"
else
confirm "部署 reward distributor？" || die "已中止"
export EXCHANGE_NEW ESG_REGISTRY_V2 SUSTAINABILITY_BADGE
LDD="$REPO_ROOT/scripts/.log-129-d.txt"
forge_run "Deploy102RewardDistributor.s.sol:Deploy102RewardDistributor" "$LDD" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "distributor 部署失敗,看 $LDD"
REWARD_DISTRIBUTOR_NEW="$(grab_addr 'EsgRewardDistributor' "$LDD")"; [[ -n "$REWARD_DISTRIBUTOR_NEW" ]] || die "撈不到 EsgRewardDistributor 位址"
export REWARD_DISTRIBUTOR_NEW
remember REWARD_DISTRIBUTOR_NEW "$REWARD_DISTRIBUTOR_NEW"
pause "Enter 繼續"
fi

# ── Stage 8 · Phase E：接金庫到登記所 + 開放鑄造 ──────────────────────
stage "Phase E — vault.setEsgRegistry + 設 cap + fundVault"
say "接上登記所後,金庫的鑄造費率才從『每檔 100』變成逐資產。"
export VAULT_PROXY_129 ESG_REGISTRY_V2
LE="$REPO_ROOT/scripts/.log-129-e.txt"
if [[ "$(cast call "$VAULT_PROXY_129" 'esgRegistry()(address)' --rpc-url "$RPC")" == "0x0000000000000000000000000000000000000000" ]]; then
  confirm "廣播 Wire129（setEsgRegistry）？" || die "已中止"
  forge_run "Wire129.s.sol:Wire129" "$LE" --private-key "$PRIVATE_KEY" --broadcast --slow \
    || die "Wire129 失敗 —— 多半是登記所沒 seed。看 $LE"
  ok "金庫已接登記所"
else
  ok "金庫已接登記所（esgRegistry != 0）—— 跳過 setEsgRegistry"
fi
cc "$VAULT_PROXY_129" 'mintFeeBpsForAsset(bytes32)(uint256)' "$(cast keccak sMSFT)";  note "期望 100（High）"
cc "$VAULT_PROXY_129" 'mintFeeBpsForAsset(bytes32)(uint256)' "$(cast keccak sNVDA)";  note "期望 10（Low）"
say ""
say "開放鑄造 —— 每檔設 cap（單位 token,18 位小數；金額跟風險組員確認）,然後 fundVault。"
say "cap 用 RISK_ROLE key（預設 = admin);fundVault 用 admin key。"
if confirm "現在逐檔設 cap？（會逐檔問金額,Enter 跳過該檔）"; then
  ask CAP_KEY "RISK_ROLE 的私鑰（Enter 用 PRIVATE_KEY）"
  for s in "${SYMS[@]}"; do
    ask CAPV "  $s 的 cap（token 數,例如 1000000,Enter 跳過）"
    if [[ -n "${CAPV:-}" ]]; then
      PRIV="${CAP_KEY:-$PRIVATE_KEY}" cs "$VAULT_PROXY_129" 'setAssetCap(bytes32,uint256)' "$(cast keccak "$s")" "$(cast to-wei "$CAPV" ether)" || true
    fi
    CAPV=""
  done
fi
ask FUND_USDC "fundVault 注入多少 USDC？（例如 100000,Enter 跳過）"
if [[ -n "${FUND_USDC:-}" ]]; then
  FW="$(cast to-wei "$FUND_USDC" ether)"
  warn "先 approve：cast send $USDC 'approve(address,uint256)' $VAULT_PROXY_129 $FW --private-key <admin>"
  cs "$USDC" 'approve(address,uint256)' "$VAULT_PROXY_129" "$FW" || true
  cs "$VAULT_PROXY_129" 'fundVault(uint256)' "$FW" || true
fi
pause "Enter 繼續"

# ── Stage 9 · Phase F：逐項驗證 ────────────────────────────────────────
stage "Phase F — Verify129（唯讀,整張相依圖）"
say "第一個不符就 revert 並印欄位名。"
export GUARDED_ORACLE_129 VAULT_PROXY_129 ESG_REGISTRY_V2 SUSTAINABILITY_BADGE \
       EXCHANGE_NEW COPYTRACKER_NEW STRATEGY_REGISTRY_NEW SESSION_MANAGER_NEW REWARD_DISTRIBUTOR_NEW
LF="$REPO_ROOT/scripts/.log-129-f.txt"
forge_run "Verify129.s.sol:Verify129" "$LF" \
  && ok "Verify129 全綠 —— 合約接線完成（畫面驗收仍要人工走 §11）" \
  || die "Verify129 失敗 —— 看 $LF 最後幾行的 MISMATCH 欄位,對照 docs/DEPLOY_129_CUTOVER.md §12"
pause "Enter 繼續"

# ── Stage 10 · 回填 addresses.ts + ABI ────────────────────────────────
stage "回填 frontend/src/contracts/addresses.ts + 複製 ABI"
warn "一次改完 —— ChainAddresses 的 exchange 欄位沒有 hasV2Stack 那種 0x0 退回閘,分批改會裂腦。"
say "V2_STACK[84532]："
patch_v2stack GuardedOracle       "$GUARDED_ORACLE_129"
patch_v2stack AssetVaultV2        "$VAULT_PROXY_129"
patch_v2stack ESGRegistryV2       "$ESG_REGISTRY_V2"
patch_v2stack SustainabilityBadge "$SUSTAINABILITY_BADGE"
say "BASE_SEPOLIA ChainAddresses："
patch_addr PerpetualExchange    "$EXCHANGE_NEW"
patch_addr StrategyRegistry     "$STRATEGY_REGISTRY_NEW"
patch_addr CopyTracker          "$COPYTRACKER_NEW"
patch_addr ESGRegistry          "$ESG_REGISTRY_V2"
patch_addr EsgRewardDistributor "$REWARD_DISTRIBUTOR_NEW"
say ""
warn "V2_STACK[84532].tokens 的 11 顆要手動貼（scripts/.tokens-129.txt）。貼成這個形狀,取代空的 tokens: {}："
if [[ -f "$REPO_ROOT/scripts/.tokens-129.txt" ]]; then
  printf '    tokens: {\n'
  while read -r s a; do printf '      %-7s "%s",\n' "$s:" "$a"; done < "$REPO_ROOT/scripts/.tokens-129.txt"
  printf '    },\n'
fi
say ""
say "複製新 ABI（只取 .abi 陣列）："
for n in PerpetualExchange CopyTracker StrategyRegistry AgentSessionManager AssetVaultV2_4 ESGRegistryV2 GuardedOracle SustainabilityBadge EsgRewardDistributor; do
  src="$CONTRACTS/out/$n.sol/$n.json"
  # AssetVaultV2_4 → 前端沿用 AssetVaultV2.json 檔名
  dstname="$n"; [[ "$n" == "AssetVaultV2_4" ]] && dstname="AssetVaultV2"
  dst="$REPO_ROOT/frontend/src/contracts/abi/$dstname.json"
  [[ -f "$src" ]] || { warn "找不到 $src"; continue; }
  jq '.abi' "$src" > "$dst" && ok "abi/$dstname.json"
done
say ""
say "git diff 檢查 addresses.ts,把 tokens 貼進去,開 PR。"
pause "貼完 tokens、確認 diff 後 Enter"

# ── Stage 11 · agent/.env + 重建 ──────────────────────────────────────
stage "agent/.env + 重建前端 / agent"
say "在 agent/.env 設（wizard 不自動改 —— 那檔有其他內容）："
say  "  SESSION_MANAGER_ADDRESS=$SESSION_MANAGER_NEW"
say  "  DEMO_SESSION_ID=0"
say  "  PERP_ADDRESS=$EXCHANGE_NEW"
say  "  KEEPER_GUARDED_ORACLE=$GUARDED_ORACLE_129"
say  "  KEEPER_VAULT_ADDRESS=$VAULT_PROXY_129"
pause "改完 agent/.env 後 Enter"
if confirm "現在跑 frontend 的 tsc + vitest？"; then
  run bash -c "cd '$REPO_ROOT/frontend' && yarn install --frozen-lockfile && yarn tsc --noEmit && yarn vitest run" || warn "前端有問題 —— 修完再部署站台"
fi
if confirm "跑 agent 的 typecheck + test？"; then
  run bash -c "cd '$REPO_ROOT/agent' && npm install && npm run typecheck && npm test" || warn "agent 有問題"
fi
say "記得：部署前端站台;重啟 signal-api / keeper / mcp-server（從 addresses.ts 讀新位址）。"
say "keeper 第一輪會為 11 檔寫新價（MockOracle + GuardedOracle）—— 盯 sBOND 有沒有 DeviationTooLarge。"
say "確認 keeper 至少跑過一輪 observeReserve()（KEEPER_VAULT_ADDRESS 已設）→ 新金庫的 ReserveObserved 事件上鏈。"
pause "Enter 進入收尾"

# ── Stage 12 · demo 策略 + 收尾 ───────────────────────────────────────
stage "demo 策略 + 收尾"
say "新 StrategyRegistry 是空的。至少 3 份 Allocation（每份 ≥3 資產、每權重 ≤5000bps、加總 10000、全 1x）。"
if confirm "用部署者帳號 registerTrader + 發 3 份（低碳保守 / 均衡 / 成長)？"; then
  cs "$STRATEGY_REGISTRY_NEW" 'registerTrader(string)' "PepeLab Demo" || true
  KA(){ cast keccak "$1"; }
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sICLN),3400,true,1),($(KA sBOND),3300,true,1),($(KA sNVDA),3300,true,1)]" || warn "低碳保守 失敗"
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sAAPL),2500,true,1),($(KA sESGU),2500,true,1),($(KA sGOLD),2500,true,1),($(KA sETH),2500,true,1)]" || warn "均衡 失敗"
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sNVDA),4000,true,1),($(KA sMSFT),3000,true,1),($(KA sGOOGL),3000,true,1)]" || warn "成長 失敗"
  ok "策略發布嘗試完成 —— /marketplace 確認看得到 3 份"
else
  warn "跳過 —— demo 前一定要有至少 3 份"
fi
say ""
say "所有新位址（也存在 $SCRATCH）："; cat "$SCRATCH"
say ""
say "還沒自動化、要你自己做的（docs/DEPLOY_129_CUTOVER.md §11 六條畫面驗收）："
step "資產頁讀得到儲備率;預言機失效時顯示「無法確認」"
step "11 檔各自顯示得出被見證的分級與筆數"
step "低碳 vs 高碳買入費率確實不同（sNVDA 0.10% / sMSFT 1.00%）"
step "試調單一資產買入費率 → 失敗;試為特定使用者豁免碳費率 → 失敗（先排練打哪個呼叫）"
step "走過 11 頁 Expert Mode"
step "把新位址 + 發布帳號更新到 issue #129"
open_url "https://github.com/zuemen/pepelab_onchain_cfd/issues/129"

finish
