#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# ==========================================================================
#  #102 四合約連鎖重部署 wizard   （中文說明 · 全程對 Base Sepolia 84532）
#
#  它做什麼：一步一步跑完 docs/DEPLOY_102_CUTOVER.md。每個「送鏈」的動作前
#  都會停下來讓你確認。可以隨時 Ctrl-C，重跑時把 scratch 檔裡已抓到的位址
#  貼回環境變數就能接續（見結尾）。
#
#  在哪跑：WSL，倉庫根目錄底下：   bash scripts/deploy-102.sh
#  先決：  foundry(forge/cast)、jq、以及環境變數
#           export PRIVATE_KEY=0x…            （見下方「金鑰」）
#           export BASE_SEPOLIA_RPC_URL=…
#           export BASESCAN_API_KEY=…          （選用，開 --verify）
#
#  金鑰：合約的現任 owner 是 0x27C21324D101e867E0634bf2ebe3F9Dcf3ACA585
#        （2026-08-07 輪替，見 docs/KEY_ROTATION_20260807.md）。它的私鑰
#        **不在 git 裡**、也不是舊的洩漏金鑰；當初存在 contracts/.env.rotation
#        （gitignored），計畫移進密碼管理器。跟執行輪替的組員 / 團隊密碼管理器要。
#        ⚠ contracts/.env.example 裡的 PRIVATE_KEY 是 Anvil 本機測試假金鑰
#          （地址 0xf39Fd6…），不要用。
#        該錢包要有 Base Sepolia ETH 付 gas。
#
#  ⚠ 這個 wizard 與它呼叫的三個 forge 腳本是在沒有 foundry 的環境寫的，
#    forge build 有過（CI），但沒對鏈實際執行過。每個 forge 步驟都對應
#    docs/DEPLOY_102_CUTOVER.md 裡的手動指令 —— 卡住就翻那份、手動跑。
#    保護不可逆步驟的是 Stage 4 的 dry-run 閘門（純讀取），一定如實反映鏈上狀態。
#
#  forge 廣播都帶 --slow（每筆等 receipt）。若 owner 帳號有 EIP-7702 delegation，
#  Base 會拒絕 forge 預派的 gapped nonce；--slow 讓 nonce 嚴格遞增。
#  （見 docs/KEY_ROTATION_20260807.md 的同一個教訓。）
# ==========================================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="$REPO_ROOT/contracts"
ADDR_TS="$REPO_ROOT/frontend/src/contracts/addresses.ts"
SCRATCH="$REPO_ROOT/scripts/.deploy-102-addresses.env"   # gitignore 建議
CHAIN=84532
RPC="${BASE_SEPOLIA_RPC_URL:-}"
FORGE_VERIFY=""
[[ -n "${BASESCAN_API_KEY:-}" ]] && FORGE_VERIFY="--verify --etherscan-api-key $BASESCAN_API_KEY"

# ── 小工具（模板函式庫之外，這個 wizard 專用）──────────────────────────────

die()  { printf '\n  %s✖ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
run()  { printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"; "$@"; }

# 把一個 export 記進 scratch 檔，重跑時可 source 回來
remember() { printf 'export %s=%s\n' "$1" "$2" >> "$SCRATCH"; ok "記下 $1=$2"; }

# 從 forge 的 -vvv 輸出裡撈「Label : 0xADDRESS」那種行
grab_addr() { grep -oE "$1[^:]*: *0x[0-9a-fA-F]{40}" "$2" | grep -oE '0x[0-9a-fA-F]{40}' | tail -1; }

# cast call，印指令 + 結果
cc() { printf '  %s· %s%s\n' "$DIM" "cast call $1 \"$2\" ${*:3}" "$RESET"; cast call "$1" "$2" "${@:3}" --rpc-url "$RPC"; }

# cast send，確認後才送
cs() {
  printf '  %s將送出：%s cast send %s "%s" %s\n' "$YELLOW" "$RESET" "$1" "$2" "${*:3}"
  confirm "送出這筆交易？" || { warn "跳過"; return 1; }
  cast send "$1" "$2" "${@:3}" --private-key "$PRIVATE_KEY" --rpc-url "$RPC"
}

# 只改 addresses.ts 的 BASE_SEPOLIA 區塊裡的一行： KEY: "0x…"
patch_addr() {
  local key="$1" val="$2"
  awk -v k="$key" -v v="$val" '
    /^const BASE_SEPOLIA/ { inblk=1 }
    inblk && /^\}/        { inblk=0 }
    inblk && $0 ~ ("^[[:space:]]*" k ":[[:space:]]*\"0x") {
      sub(/"0x[0-9a-fA-F]+"/, "\"" v "\""); print; next
    }
    { print }
  ' "$ADDR_TS" > "$ADDR_TS.tmp" && mv "$ADDR_TS.tmp" "$ADDR_TS"
  ok "addresses.ts BASE_SEPOLIA.$key → $val"
}

forge_run() {   # forge_run <ScriptFile:Contract> <logfile> [extra forge args...]
  local target="$1" logf="$2"; shift 2
  ( cd "$CONTRACTS" && forge script "script/$target" --rpc-url "$RPC" "$@" -vvv ) 2>&1 | tee "$logf"
  return "${PIPESTATUS[0]}"
}

# ==========================================================================

banner "#102 四合約連鎖重部署"

# ── Stage 1 · 環境檢查 ────────────────────────────────────────────────────
stage "環境檢查"
say "確認工具、金鑰、餘額、以及你這把金鑰真的是合約 owner。"
for c in forge cast jq git awk; do command -v "$c" >/dev/null || die "找不到 $c —— 先裝好（foundry / apt install jq）"; done
[[ -n "${PRIVATE_KEY:-}" ]] || die "沒設 PRIVATE_KEY。現任 owner 是 0x27C21324D101e867E0634bf2ebe3F9Dcf3ACA585（2026-08-07 輪替，key 在 contracts/.env.rotation / 密碼管理器 / 組員手上，見 docs/KEY_ROTATION_20260807.md）。contracts/.env.example 的那把是 Anvil 假金鑰，不要用。"
[[ -n "$RPC" ]] || die "沒設 BASE_SEPOLIA_RPC_URL"
DEPLOYER="$(cast wallet address --private-key "$PRIVATE_KEY")" || die "PRIVATE_KEY 格式不對"
ok "部署者地址：$DEPLOYER"
EXPECTED_OWNER="0x27C21324D101e867E0634bf2ebe3F9Dcf3ACA585"
if [[ "${DEPLOYER,,}" == "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" ]]; then
  die "這是 Anvil 測試帳號 #0（contracts/.env.example 的預設值）—— 它不擁有任何 Base Sepolia 合約。換成 $EXPECTED_OWNER 的真金鑰。"
fi
CID="$(cast chain-id --rpc-url "$RPC")"; [[ "$CID" == "$CHAIN" ]] || die "RPC 指向 chain $CID，不是 Base Sepolia（$CHAIN）"
BAL_WEI="$(cast balance "$DEPLOYER" --rpc-url "$RPC")"
BAL_ETH="$(cast from-wei "$BAL_WEI")"
say "ETH 餘額：$BAL_ETH"
awk -v b="$BAL_ETH" 'BEGIN{ if (b+0 < 0.05) exit 1 }' || warn "餘額偏低，部署約需 15–20 筆交易 —— 先去水龍頭領 ETH：https://docs.base.org/chain/network-faucets"
OWNER_EX="$(cast call 0xEf75ECA6514cE96B18382E921aC6190a0cF8c072 'owner()(address)' --rpc-url "$RPC")"
if [[ "${OWNER_EX,,}" == "${DEPLOYER,,}" ]]; then
  ok "你這把金鑰是舊 PerpetualExchange 的 owner"
else
  warn "舊 PerpetualExchange 的 owner 是 $OWNER_EX，不是你（$DEPLOYER）。"
  if [[ "${OWNER_EX,,}" == "${EXPECTED_OWNER,,}" ]]; then
    warn "鏈上 owner 就是輪替後的 $EXPECTED_OWNER —— 你手上這把不是它。"
    warn "跟執行 2026-08-07 輪替的組員 / 密碼管理器要那把 key。"
  fi
  warn "§5 那些 onlyOwner 的重接線（setExchange / setCopyTracker / setRwaAsset / 撤舊 session manager）會 revert。"
  confirm "還是要繼續（不建議）" || die "換成 owner 金鑰再來"
fi
if [[ -s "$SCRATCH" ]]; then
  say "偵測到上次執行的 scratch 檔：$SCRATCH"
  cat "$SCRATCH"
  if confirm "這是接續執行 —— 把裡面的位址 source 回來（跳過已完成的部署）？"; then
    # shellcheck disable=SC1090
    source "$SCRATCH"; ok "已載入既有位址"
  else
    : > "$SCRATCH"; printf '# #102 部署 — 抓到的新位址（可 source 回來接續）\n' >> "$SCRATCH"
  fi
else
  : > "$SCRATCH"; printf '# #102 部署 — 抓到的新位址（可 source 回來接續）\n' >> "$SCRATCH"
fi
pause "檢查通過。Enter 繼續"

# ── Stage 2 · 編譯 ────────────────────────────────────────────────────────
stage "編譯合約"
say "forge build —— 產生 ABI（等一下要複製到前端）並驗證 §2 的新腳本可編譯。"
run bash -c "cd '$CONTRACTS' && forge build" || die "forge build 失敗 —— 先修編譯錯誤（§2 的腳本可能要調）"
ok "編譯通過"
pause "Enter 繼續"

# ── Stage 3 · 部署碳見證合約 ─────────────────────────────────────────────
stage "部署 ESGRegistryV2 + SustainabilityBadge，並見證 11 個資產"
if [[ -n "${ESG_REGISTRY_V2:-}" && -n "${SUSTAINABILITY_BADGE:-}" ]]; then
  ok "已完成（ESGRegistryV2=$ESG_REGISTRY_V2）—— 跳過"; pause "Enter 繼續"
else
say "這一步會送鏈：部署兩個合約、授 ATTESTOR_ROLE、寫 11 筆見證。"
say "碳強度數字對齊 docs/data/carbon-intensity.md（非營收資產是分級『placement』值，"
say "見腳本 NatSpec —— 口試前要組員點頭）。"
confirm "開始部署碳見證合約？" || die "已中止"
L1="$REPO_ROOT/scripts/.log-carbon.txt"
forge_run "Deploy102CarbonRegistry.s.sol:Deploy102CarbonRegistry" "$L1" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "碳見證部署失敗 —— 看 $L1，別重跑整段（會 fork）；可用 cast 補完"
ESG_REGISTRY_V2="$(grab_addr 'ESGRegistryV2' "$L1")";  [[ -n "$ESG_REGISTRY_V2" ]] || die "撈不到 ESGRegistryV2 位址，看 $L1"
SUSTAINABILITY_BADGE="$(grab_addr 'SustainabilityBadge' "$L1")"; [[ -n "$SUSTAINABILITY_BADGE" ]] || die "撈不到 SustainabilityBadge 位址"
export ESG_REGISTRY_V2 SUSTAINABILITY_BADGE
remember ESG_REGISTRY_V2 "$ESG_REGISTRY_V2"
remember SUSTAINABILITY_BADGE "$SUSTAINABILITY_BADGE"
say "驗證見證有落地："
cc "$ESG_REGISTRY_V2" 'medianCarbonIntensity(bytes32)(uint256,uint256,uint256,bool)' "$(cast keccak sMSFT)"
pause "看到 median 非零、最後一個布林是 true 就對了。Enter 繼續"
fi

# ── Stage 4 · 清空檢查（dry-run，不送鏈）─────────────────────────────────
stage "清空檢查 —— 舊 exchange 還有幾個未平倉部位"
say "純讀取，什麼都不送。只要非零就不能往下走（§4）。"
L2="$REPO_ROOT/scripts/.log-dryrun.txt"
export DRY_RUN=true
forge_run "Redeploy102Exchange.s.sol:Redeploy102Exchange" "$L2" || { unset DRY_RUN; die "dry-run 失敗，看 $L2"; }
unset DRY_RUN   # ← 一定要 unset，否則 Stage 5 的廣播也會變成 dry-run
if grep -q "0 open positions on the old exchange" "$L2"; then
  ok "舊 exchange 0 未平倉 —— 可以切換"
else
  OPENCNT="$(grep -oiE 'open positions[[:space:]:]+[0-9]+' "$L2" | grep -oE '[0-9]+' | tail -1)"
  warn "舊 exchange 還有 ${OPENCNT:-一些} 個未平倉部位（上方 survey 有 id / owner）。"
  say  ""
  say  "理想做法：每個 owner 自己平倉 + 提保證金，把數字清到 0，然後重跑本 wizard"
  say  "  cast send $OLD_EXCHANGE 'closePosition(uint256)' <id> --private-key <owner_key> --rpc-url \$BASE_SEPOLIA_RPC_URL"
  say  "  cast send $OLD_EXCHANGE 'withdrawMargin(uint256)' <amount> --private-key <owner_key> --rpc-url \$BASE_SEPOLIA_RPC_URL"
  say  ""
  warn "但如果部位的 owner 是已失控/sweeper 佔用的金鑰（例如舊的 0xE80A8136…），"
  warn "沒人能平它 —— 只能等它被清算，或帶著它切換。"
  warn "帶著未平倉切換的後果：Stage 5 的 InsuranceVault.setExchange 之後，"
  warn "那些部位在舊 exchange 上需要 bailout 時會 revert，平不掉也清算不了。"
  say  ""
  if confirm "我了解風險，仍要帶著這 ${OPENCNT:-?} 個未平倉部位繼續切換"; then
    warn "已選擇帶著未平倉部位繼續 —— Stage 5 的腳本會把這記成一個刻意的選擇。"
  else
    die "先去清空未平倉部位，再重跑本 wizard（會從 $SCRATCH 接續已完成的部署）"
  fi
fi
pause "Enter 進入不可逆的部署階段"

# ── Stage 5 · 四合約連鎖重部署（不可逆點）──────────────────────────────
stage "四合約連鎖重部署（PerpetualExchange + StrategyRegistry + CopyTracker + AgentSessionManager）"
if [[ -n "${EXCHANGE_NEW:-}" ]]; then
  ok "已完成（PerpetualExchange_NEW=$EXCHANGE_NEW）—— 跳過"; pause "Enter 繼續"
else
warn "這一步的最後兩個呼叫（InsuranceVault/FeeRouter.setExchange）之後，舊 exchange 上"
warn "虧損部位就平不掉了。確定舊 exchange 已清空、前面兩天緩衝還在。"
confirm "廣播四合約重部署？" || die "已中止（什麼都沒送）"
L3="$REPO_ROOT/scripts/.log-chain.txt"
forge_run "Redeploy102Exchange.s.sol:Redeploy102Exchange" "$L3" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "重部署跑到一半失敗 —— 看 $L3 與 contracts/broadcast/Redeploy102Exchange.s.sol/$CHAIN/run-latest.json。別重跑整段；用 cast 補完剩下的 onlyOwner setter。"
EXCHANGE_NEW="$(grab_addr 'PerpetualExchange_NEW' "$L3")"
STRATEGY_REGISTRY_NEW="$(grab_addr 'StrategyRegistry_NEW' "$L3")"
COPY_TRACKER_NEW="$(grab_addr 'CopyTracker_NEW' "$L3")"
SESSION_MANAGER_NEW="$(grab_addr 'AgentSessionManager_NEW' "$L3")"
for v in EXCHANGE_NEW STRATEGY_REGISTRY_NEW COPY_TRACKER_NEW SESSION_MANAGER_NEW; do
  [[ -n "${!v}" ]] || die "撈不到 $v，看 $L3"
done
export EXCHANGE_NEW STRATEGY_REGISTRY_NEW COPY_TRACKER_NEW SESSION_MANAGER_NEW
remember EXCHANGE_NEW "$EXCHANGE_NEW"
remember STRATEGY_REGISTRY_NEW "$STRATEGY_REGISTRY_NEW"
remember COPY_TRACKER_NEW "$COPY_TRACKER_NEW"
remember SESSION_MANAGER_NEW "$SESSION_MANAGER_NEW"
ok "四合約已上鏈"
pause "Enter 繼續"
fi

# ── Stage 6 · 部署 EsgRewardDistributor（要在 exchange 之後）───────────
stage "部署 EsgRewardDistributor（發 SustainabilityBadge，不發 PEPE）"
if [[ -n "${ESG_REWARD_DISTRIBUTOR_NEW:-}" ]]; then
  ok "已完成（$ESG_REWARD_DISTRIBUTOR_NEW）—— 跳過"; pause "Enter 繼續"
else
confirm "部署 reward distributor？" || die "已中止"
L4="$REPO_ROOT/scripts/.log-reward.txt"
forge_run "Deploy102RewardDistributor.s.sol:Deploy102RewardDistributor" "$L4" --private-key "$PRIVATE_KEY" --broadcast --slow $FORGE_VERIFY \
  || die "distributor 部署失敗，看 $L4"
ESG_REWARD_DISTRIBUTOR_NEW="$(grab_addr 'EsgRewardDistributor' "$L4")"
[[ -n "$ESG_REWARD_DISTRIBUTOR_NEW" ]] || die "撈不到 EsgRewardDistributor 位址"
remember ESG_REWARD_DISTRIBUTOR_NEW "$ESG_REWARD_DISTRIBUTOR_NEW"
pause "Enter 繼續"
fi

# ── Stage 7 · 鏈上健檢 ───────────────────────────────────────────────────
stage "鏈上健檢（cast call，純讀取）"
say "每一行都該符合右邊的期望值。"
cc "$EXCHANGE_NEW" 'FUNDING_INTERVAL()(uint256)';                                       note "期望 28800（= 8h）"
cc "$EXCHANGE_NEW" 'copyTracker()(address)';                                             note "期望 $COPY_TRACKER_NEW"
cc 0x00f6cf0113399a7A451c7f85fe094a28092d3e0c 'copyTracker()(address)';                  note "FeeRouter，期望 $COPY_TRACKER_NEW"
cc 0x01aEB530bcFc69f036309ffe55acc7eA6C5a28Fe 'copyTracker()(address)';                  note "TraderStake，期望 $COPY_TRACKER_NEW"
cc 0xB364E2e3e1e7a2b033eF03a4ACceF42066F3D812 'exchange()(address)';                     note "InsuranceVault，期望 $EXCHANGE_NEW"
cc "$EXCHANGE_NEW" 'authorizedAgents(address)(bool)' "$SESSION_MANAGER_NEW";              note "期望 true"
cc "$EXCHANGE_NEW" 'authorizedAgents(address)(bool)' 0x5Ebcc64C712C5a26119789dCbD0753981dc518E8; note "期望 false（新 exchange）"
cc 0xEf75ECA6514cE96B18382E921aC6190a0cF8c072 'authorizedAgents(address)(bool)' 0x5Ebcc64C712C5a26119789dCbD0753981dc518E8; note "期望 false（舊 exchange 已撤銷）"
cc "$EXCHANGE_NEW" 'maxLeverageForAsset(bytes32)(uint256)' "$(cast keccak sMSFT)";       note "高碳，期望 1"
cc "$EXCHANGE_NEW" 'tradingFeeBpsForAsset(bytes32)(uint256)' "$(cast keccak sMSFT)";     note "高碳，期望 100"
cc "$EXCHANGE_NEW" 'maxLeverageForAsset(bytes32)(uint256)' "$(cast keccak sNVDA)";       note "低碳，期望 5"
confirm "以上都符合？" || die "有對不上的 —— 看 docs/DEPLOY_102_CUTOVER.md §10 排錯，別往下走"
pause "Enter 繼續"

# ── Stage 8 · 更新 addresses.ts + ABI ───────────────────────────────────
stage "更新 frontend/src/contracts/addresses.ts（BASE_SEPOLIA 區塊）+ 複製 ABI"
say "會直接改檔案 —— 改完 git diff 看一下。"
patch_addr PerpetualExchange   "$EXCHANGE_NEW"
patch_addr StrategyRegistry    "$STRATEGY_REGISTRY_NEW"
patch_addr CopyTracker         "$COPY_TRACKER_NEW"
patch_addr ESGRegistry         "$ESG_REGISTRY_V2"
patch_addr EsgRewardDistributor "$ESG_REWARD_DISTRIBUTOR_NEW"
say "複製新 ABI（只取 .abi 陣列 —— 前端要的是 [ ... ] 不是整份 forge artifact，同 deploy-anvil.sh）："
for n in PerpetualExchange CopyTracker StrategyRegistry AgentSessionManager ESGRegistryV2 SustainabilityBadge EsgRewardDistributor; do
  src="$CONTRACTS/out/$n.sol/$n.json"; dst="$REPO_ROOT/frontend/src/contracts/abi/$n.json"
  if [[ ! -f "$src" ]]; then warn "找不到 $src（前端可能不需要這個 ABI）"; continue; fi
  if command -v jq >/dev/null 2>&1; then
    jq '.abi' "$src" > "$dst" && ok "abi/$n.json"
  elif command -v node >/dev/null 2>&1; then
    node -e "require('fs').writeFileSync('$dst', JSON.stringify(JSON.parse(require('fs').readFileSync('$src','utf8')).abi,null,2)+'\n')" && ok "abi/$n.json"
  else
    warn "沒有 jq 也沒有 node —— 手動：jq '.abi' $src > $dst"
  fi
done
warn "AgentSessionManager 位址不在 addresses.ts —— 在 agent/.env 設："
say  "  SESSION_MANAGER_ADDRESS=$SESSION_MANAGER_NEW"
say  "  DEMO_SESSION_ID=0"
say  "  PERP_ADDRESS=$EXCHANGE_NEW"
pause "手動改完 agent/.env 後 Enter"

# ── Stage 9 · 重建前端 + agent ─────────────────────────────────────────
stage "重建前端 + agent（驗證接線）"
say "跑 build/test；紅的話多半是 ABI 沒複製到或 addresses.ts 沒改乾淨。"
if confirm "現在跑 frontend 的 yarn build + yarn test？（可能要幾分鐘）"; then
  run bash -c "cd '$REPO_ROOT/frontend' && yarn install --frozen-lockfile && yarn build && yarn test" || warn "前端 build/test 有問題 —— 修完再部署站台"
fi
if confirm "跑 agent 的 typecheck + test + bundle？"; then
  run bash -c "cd '$REPO_ROOT/agent' && npm install && npm run typecheck && npm test && npm run bundle:vercel" || warn "agent 有問題 —— 修完再重啟 keeper/signal-api/mcp"
fi
say "記得重啟：signal-api、keeper（或它的 CI 排程）、mcp-server —— 它們從 addresses.ts 讀新位址。"
pause "Enter 繼續"

# ── Stage 10 · 注資 MockSwapRouter ───────────────────────────────────────
stage "注資 MockSwapRouter（/exchange 的 ETH↔USDC 兌換要用）"
say "MockSwapRouter = 0xC9b0e5C219AA1B3eB00E92Fd9a883B182F0AE8Ae"
ask ROUTER_ETH "要注入多少 ETH？（例如 0.02，Enter 跳過）"
if [[ -n "${ROUTER_ETH:-}" ]]; then
  cs 0xC9b0e5C219AA1B3eB00E92Fd9a883B182F0AE8Ae 'fundRouter()' --value "$(cast to-wei "$ROUTER_ETH")" \
    && ok "已注入 $ROUTER_ETH ETH" || warn "注資失敗或跳過 —— 確認 fundRouter() 是不是正確的函式名（見合約）"
else
  warn "跳過 —— 記得之後手動注資，否則 /exchange 兌換會 revert"
fi
pause "Enter 繼續"

# ── Stage 11 · 發布 3 份 demo 配置 ──────────────────────────────────────
stage "發布 3 份 demo Allocation 到新的 StrategyRegistry"
say "新註冊表是空的。這裡從你的部署者帳號發 3 份（低碳保守 / 均衡 / 成長）。"
say "若 registry 建構時綁了 TraderStake 且你質押不足，publishStrategy 會 revert —— 那就手動補質押後再跑本段。"
if confirm "用部署者帳號 registerTrader + 發 3 份策略？"; then
  cs "$STRATEGY_REGISTRY_NEW" 'registerTrader(string)' "PepeLab Demo" || true
  # Allocation tuple: (bytes32 asset, uint256 weightBps, bool isLong, uint256 leverage)
  KA(){ cast keccak "$1"; }
  # 低碳保守：sICLN 3400 / sBOND 3300 / sNVDA 3300
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sICLN),3400,true,1),($(KA sBOND),3300,true,1),($(KA sNVDA),3300,true,1)]" || warn "低碳保守 發布失敗"
  # 均衡：sAAPL/sESGU/sGOLD/sETH 各 2500
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sAAPL),2500,true,1),($(KA sESGU),2500,true,1),($(KA sGOLD),2500,true,1),($(KA sETH),2500,true,1)]" || warn "均衡 發布失敗"
  # 成長：sNVDA 4000 / sMSFT 3000 / sGOOGL 3000
  cs "$STRATEGY_REGISTRY_NEW" 'publishStrategy((bytes32,uint256,bool,uint256)[])' \
    "[($(KA sNVDA),4000,true,1),($(KA sMSFT),3000,true,1),($(KA sGOOGL),3000,true,1)]" || warn "成長 發布失敗"
  ok "策略發布嘗試完成 —— 到 /marketplace 確認看得到 3 份"
else
  warn "跳過 —— demo 前一定要有至少 3 份（見 §8）"
fi
pause "Enter 進入收尾"

# ── Stage 12 · 收尾 ─────────────────────────────────────────────────────
stage "收尾與剩下要手動做的事"
say "所有新位址（也存在 $SCRATCH）："
cat "$SCRATCH"
say ""
say "還沒自動化、要你自己做的："
step "git diff 檢查 addresses.ts + ABI，開 PR"
step "部署前端站台（Vercel）"
step "重啟 signal-api / keeper / mcp-server；確認 keeper 為 11 個資產寫新價、sBOND 沒 DeviationTooLarge"
step "走過 11 頁 Expert Mode（§9.2）"
step "排練『試圖為特定使用者豁免碳費率 → revert』那一幕（§9.3）"
step "把新位址 + 發布帳號更新到 issue #102"
open_url "https://github.com/zuemen/pepelab_onchain_cfd/issues/102"

finish
